version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - mkdir -p build/python
      - grep -ivEe '^boto(3|core)[=<>]' requirements.txt | pip install -r /dev/stdin --target build/python
      - pip install --no-dependencies --target build/python .
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes

# vim: ts=2 sts=2 sw=2 expandtab
